[package]
name = "bevy_smud"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
description = "2d sdf shape renderer plugin for Bevy"
keywords = ["gamedev", "bevy", "sdf"]
categories = ["game-development", "rendering", "graphics"]
repository = "https://github.com/johanhelsing/bevy_smud"

[dependencies]
bevy = { version = "0.7.0", default-features = false, features = ["render"] }
bytemuck = "1.7"
bitflags = "1.2"
copyless = "0.1"
bevy-inspector-egui = { version = "0.10", optional = true }

[dev-dependencies]
bevy_pancam = "0.3"
bevy_lospec = "0.1.1"
bevy_asset_loader = "0.10"
rand = "0.8"
bevy = { version = "0.7.0", default-features = false, features = [
    "render",
    "bevy_winit",
    "filesystem_watcher"
] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3