[package]
name = "bevy_so_smooth"
version = "0.1.0"
edition = "2021"

[features]
smud_shader_hot_reloading = ["bevy/bevy_shader_hot_reloading"]

[dependencies]
bevy = { version = "0.6.0", default-features = false, features = ["render"] }
bytemuck = "1.7"
bitflags = "1.2"
copyless = "0.1"

[dev-dependencies]
bevy = "0.6"
bevy_pancam = "0.2"
bevy_lospec = { git = "https://github.com/johanhelsing/bevy_lospec", branch = "main" }
bevy_asset_loader = "0.8"
rand = "0.8"

[patch.crates-io]
bevy = { git = "https://github.com/superdump/bevy", branch = "hot-reload-core-shaders" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3