[package]
name = "bevy_smud"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
description = "2d sdf shape renderer plugin for Bevy"
keywords = ["gamedev", "bevy", "sdf"]
categories = ["game-development", "rendering", "graphics"]
repository = "https://github.com/johanhelsing/bevy_smud"

[dependencies]
bevy = { version = "0.6.0", default-features = false, features = ["render"] }
bytemuck = "1.7"
bitflags = "1.2"
copyless = "0.1"

[dev-dependencies]
bevy = "0.6"
bevy_pancam = "0.2"
bevy_lospec = { git = "https://github.com/johanhelsing/bevy_lospec", branch = "main" }
bevy_asset_loader = "0.8"
rand = "0.8"

# [features]
# smud_shader_hot_reloading = ["bevy/bevy_shader_hot_reloading"]

# [patch.crates-io]
# bevy = { git = "https://github.com/superdump/bevy", branch = "hot-reload-core-shaders" }
# bevy = { path = "../bevy" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3