[package]
name = "bevy_so_smooth"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6.0", default-features = false, features = ["render"] }
bytemuck = "1.7"

[dev-dependencies]
bevy = "0.6"